site_name: The Bali JavaScript Engine
site_url: https://docs.xtrayambak.xyz
docs_dir: docs/

theme:
  name: material
  icon:
    repo: fontawesome/brands/github

repo_name: ferus-web/bali
repo_url: https://github.com/ferus-web/bali
copyright: Copyright &copy; 2024 - 2025 Trayambak Rai

use_directory_urls: true

nav:
  - Getting started with Bali: MANUAL.md
  - Bali's Heap: HEAP.md
  - Bali's interpreter: PULSAR.md
  - Code Style: CODE_STYLE.md
  - Bali's JIT compilers:
    - Baseline: jit/BASELINE.md
    - Midtier/Madhyasthal: jit/MADHYASTHAL.md
