# Used for test262.fyi

name: Build artifacts
on: push

jobs:
  build:
    runs-on: fedora-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v4
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
          restore-keys: |
            ${{ runner.os }}-nimble-
      - uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: '2.2.0'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: sudo dnf install simdutf simdutf-devel
      - run: nimble build --define:release --out:./
      - run: ls bin/

      - name: Upload Build Artifact (balde)
        uses: actions/upload-artifact@v4
        with:
          name: Balde
          path: bin/balde 

      - name: Upload Build Artifacts (test262)
        uses: actions/upload-artifact@v4
        with:
          name: Test262
          path: bin/test262
