name: Run internal tests
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v4
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
          restore-keys: |
            ${{ runner.os }}-nimble-
      - uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: '2.2.0'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Bali's internal test suite
        uses: docker://fedora:latest
        with:
          args: |
            bash -c "
            sudo dnf install cmake make gcc gcc-c++ gmp gmp-devel git -y &&
            curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh &&
            chmod +x ./init.sh &&
            git config --global --add safe.directory /github/workspace &&

            git clone https://github.com/simdutf/simdutf && cd simdutf && cmake . && sudo make install -j$(nproc) && cd .. &&

            ./init.sh --yes &&
            export PATH="$HOME/.nimble/bin:$PATH" &&
            nimble test
            "
