name: Deploy docs site

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material

      - name: Build and deploy
        run: |
          cp README.md docs/index.md
          sed -i 's/\\//g' docs/index.md
          mkdocs gh-deploy --force --config-file mkdocs.yml
