name: Static analyzer
on: [push, pull_request]

jobs:
  analyze:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: '2.2.0'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libpcre3-dev

      - name: Run Nimble Analyze
        id: analyze
        run: |
          set -o pipefail
          nimble analyze | sed -E 's/\x1B\[[0-9;]*[mK]//g' | tee nimalyzer.log

      - name: Upload failure logs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: static-analyzer-${{ matrix.runs-on }}
          path: nimalyzer.log
